### ISSUE TITLE
Add an image to the story

### ISSUE THREAD

**Issue by klafond** [CMPUT301F13T05/Team05_CYOA#39]
can be done in while with creating your own story, or editing another persons story.

**Comment by jmalina** [comment]
I'm gonna try to do this. Kevin will help too I think.

**Comment by jmalina** [comment]
Okay so I'm well on my way with this, we can put an image into a imageView and then go out and come back in and it's still there. I wrote a method in  localStorageController to  add an image to an images table (which i made in dbHelper). I also wrote an appropriate getter for it which pulls a singular image out of the localStorageController for that fragment and displays it, it also has exception handlers for if there is no image it won't crash. 

Left to do on this topic:
- Port the same functionality over into edit Fragments (some copy paste)
- Make sure you can overwrite photo's (probably to do with how I'm storing/getting photo's )
- Let the author add more then one photo?? (Do we want this?... Probably...)
- Maybe put these annotations into a gallery-style view (to do with switching the view, and then make gathering of image paths a list instead of singular, can probably change my getter).
